[build]
   builder = "nixpacks"
   buildCommand = "cd backend && pip install flask flask_cors gunicorn"
   
   [deploy]
   startCommand = "cd backend && gunicorn api:app"
   restartPolicyType = "on_failure"